BUFFER_SIZE = 4096
FILENAME_SIZE = 30
FILEHEADER_SIZE = 10

LS = 'ls'
GET = 'get'
PUT = 'put'
QUIT = 'quit'
CD = 'cd'
CWD = 'cwd'
MKDIR = 'mkdir'
CLEAR = 'clear'
ACCEPTED_COMMANDS = (LS, GET, PUT, QUIT, CD, MKDIR, CWD, CLEAR)
